"""Marker-by-marker comparison of GenomeX against real BUSCO.

GenomeX calls its completeness scan "BUSCO-compatible". That is a claim, and this
script is the test of it: run both tools over the same genomes with the same
lineage, then compare not the headline percentages but the classification of each
individual marker.

Aggregate agreement is the weaker check and can hide real disagreement -- two
tools both reporting 100% complete may still disagree on which markers are
duplicated, which is precisely the number the contamination module consumes.

Usage:
    python bench/compare_to_busco.py --genomex runs/demo-rhizobia \\
        --busco bench/busco_out --out docs/benchmark-busco.md
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

CLASSES = ["Complete", "Duplicated", "Fragmented", "Missing"]


def load_genomex_markers(run_dir: Path) -> dict[str, dict[str, str]]:
    """genome -> {busco_id: status} from each genomes/<name>/markers.tsv."""
    out: dict[str, dict[str, str]] = {}
    for tsv in sorted(run_dir.glob("genomes/*/markers.tsv")):
        genome = tsv.parent.name
        status: dict[str, str] = {}
        for line in tsv.read_text(encoding="utf-8").splitlines()[1:]:
            if not line.strip():
                continue
            bid, st = line.split("\t")[:2]
            status[bid] = st
        out[genome] = status
    return out


def load_busco_markers(busco_dir: Path) -> dict[str, dict[str, str]]:
    """genome -> {busco_id: status} from each BUSCO run's full_table.tsv.

    BUSCO writes one row per copy for duplicated markers, so a marker seen twice
    is Duplicated regardless of which row is read last.
    """
    out: dict[str, dict[str, str]] = {}
    for table in sorted(busco_dir.glob("*/run_*/full_table.tsv")):
        genome = table.parent.parent.name
        status: dict[str, str] = {}
        for line in table.read_text(encoding="utf-8").splitlines():
            if line.startswith("#") or not line.strip():
                continue
            fields = line.split("\t")
            if len(fields) < 2:
                continue
            bid, st = fields[0], fields[1]
            if bid in status and status[bid] == "Complete" and st == "Complete":
                st = "Duplicated"
            status[bid] = st
        out[genome] = status
    return out


def load_busco_summary(busco_dir: Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for js in sorted(busco_dir.glob("*/short_summary.*.json")):
        genome = js.parent.name
        data = json.loads(js.read_text(encoding="utf-8"))
        out[genome] = data.get("results", data)
    return out


def load_genomex_summary(run_dir: Path) -> dict[str, dict]:
    data = json.loads((run_dir / "genomex.json").read_text(encoding="utf-8"))
    return {g["genome"]: g["markers"] for g in data["genomes"]}


def confusion(gx: dict[str, str], bu: dict[str, str]) -> tuple[Counter, list[tuple]]:
    """Counter of (genomex_class, busco_class) plus the list of disagreements."""
    pairs: Counter = Counter()
    diffs: list[tuple] = []
    for bid in sorted(set(gx) | set(bu)):
        a, b = gx.get(bid, "Absent"), bu.get(bid, "Absent")
        pairs[(a, b)] += 1
        if a != b:
            diffs.append((bid, a, b))
    return pairs, diffs


def _pct(n: int, d: int) -> str:
    return f"{100.0 * n / d:.1f}%" if d else "-"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--genomex", required=True, type=Path, help="a GenomeX --outdir")
    ap.add_argument("--busco", required=True, type=Path, help="directory of BUSCO output dirs")
    ap.add_argument("--out", type=Path, default=Path("docs/benchmark-busco.md"))
    ap.add_argument("--lineage", default="bacteria_odb10")
    args = ap.parse_args()

    gx_markers = load_genomex_markers(args.genomex)
    bu_markers = load_busco_markers(args.busco)
    gx_sum = load_genomex_summary(args.genomex)
    bu_sum = load_busco_summary(args.busco)

    shared = sorted(set(gx_markers) & set(bu_markers))
    if not shared:
        print(f"no genomes in common.\n  genomex: {sorted(gx_markers)}\n  busco:   {sorted(bu_markers)}")
        return 1

    lines: list[str] = []
    lines.append("# GenomeX vs BUSCO")
    lines.append("")
    lines.append(
        "GenomeX describes its completeness scan as *BUSCO-compatible*: HMMER run "
        "directly against the OrthoDB v10 profiles BUSCO ships, with BUSCO's own "
        "score and length cutoffs applied. This page tests that description "
        f"against BUSCO itself on `{args.lineage}`, marker by marker."
    )
    lines.append("")
    lines.append("Generated by `bench/compare_to_busco.py`; rerun with `bench/run_busco.sh`.")
    lines.append("")

    # ---- headline table --------------------------------------------------
    lines.append("## Headline numbers")
    lines.append("")
    lines.append("| genome | tool | C | S | D | F | M | completeness |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for g in shared:
        gs, bs = gx_sum.get(g, {}), bu_sum.get(g, {})
        n = gs.get("markers_total", 124)
        lines.append(
            f"| {g} | GenomeX | {gs.get('complete','-')} | {gs.get('single_copy','-')} | "
            f"{gs.get('duplicated','-')} | {gs.get('fragmented','-')} | {gs.get('missing','-')} | "
            f"{gs.get('completeness_percent','-')}% |"
        )
        b_complete = bs.get("Complete")
        b_single = bs.get("Single copy")
        b_dup = bs.get("Multi copy")
        b_frag = bs.get("Fragmented")
        b_miss = bs.get("Missing")
        b_pct = round(100.0 * b_complete / n, 2) if isinstance(b_complete, int) else "-"
        lines.append(
            f"| {g} | BUSCO | {b_complete} | {b_single} | {b_dup} | {b_frag} | {b_miss} | {b_pct}% |"
        )
    lines.append("")

    # ---- per-marker agreement -------------------------------------------
    lines.append("## Per-marker agreement")
    lines.append("")
    lines.append("| genome | markers | identical calls | agreement |")
    lines.append("|---|---|---|---|")
    total_pairs: Counter = Counter()
    all_diffs: dict[str, list[tuple]] = {}
    for g in shared:
        pairs, diffs = confusion(gx_markers[g], bu_markers[g])
        total_pairs += pairs
        all_diffs[g] = diffs
        n = sum(pairs.values())
        same = sum(v for (a, b), v in pairs.items() if a == b)
        lines.append(f"| {g} | {n} | {same} | {_pct(same, n)} |")
    n_all = sum(total_pairs.values())
    same_all = sum(v for (a, b), v in total_pairs.items() if a == b)
    lines.append(f"| **all** | **{n_all}** | **{same_all}** | **{_pct(same_all, n_all)}** |")
    lines.append("")

    # ---- confusion matrix ------------------------------------------------
    lines.append("## Confusion matrix, pooled")
    lines.append("")
    lines.append("Rows are GenomeX, columns BUSCO.")
    lines.append("")
    observed = sorted({a for a, _ in total_pairs} | {b for _, b in total_pairs})
    order = [c for c in CLASSES if c in observed] + [c for c in observed if c not in CLASSES]
    lines.append("| GenomeX \\ BUSCO | " + " | ".join(order) + " |")
    lines.append("|---" * (len(order) + 1) + "|")
    for a in order:
        row = [str(total_pairs.get((a, b), 0)) for b in order]
        lines.append(f"| **{a}** | " + " | ".join(row) + " |")
    lines.append("")

    # ---- disagreements ---------------------------------------------------
    lines.append("## Where they disagree")
    lines.append("")
    disagreements = sum(len(d) for d in all_diffs.values())
    if not disagreements:
        lines.append("No disagreements on any marker in any genome.")
    else:
        kinds = Counter((a, b) for diffs in all_diffs.values() for _, a, b in diffs)
        lines.append("| GenomeX called | BUSCO called | markers |")
        lines.append("|---|---|---|")
        for (a, b), n in kinds.most_common():
            lines.append(f"| {a} | {b} | {n} |")
        lines.append("")
        lines.append("<details><summary>Every disagreeing marker</summary>")
        lines.append("")
        lines.append("| genome | marker | GenomeX | BUSCO |")
        lines.append("|---|---|---|---|")
        for g in shared:
            for bid, a, b in all_diffs[g]:
                lines.append(f"| {g} | `{bid}` | {a} | {b} |")
        lines.append("")
        lines.append("</details>")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"genomes compared: {len(shared)}")
    print(f"markers compared: {n_all}")
    print(f"identical calls:  {same_all} ({_pct(same_all, n_all)})")
    print(f"disagreements:    {disagreements}")
    for (a, b), n in Counter(
        (a, b) for diffs in all_diffs.values() for _, a, b in diffs
    ).most_common(8):
        print(f"   GenomeX {a:<11} vs BUSCO {b:<11} {n}")
    print(f"written: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
